# Generated by Django 5.0.4 on 2024-06-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_newequipment_equipment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipment',
            new_name='AllEquipment',
        ),
    ]
