# Generated by Django 5.0.4 on 2024-06-09 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_equipment_allequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentOnMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.allequipment')),
            ],
        ),
    ]
