# Generated by Django 5.0.4 on 2024-06-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_equipmentonmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allequipment',
            name='equipment_description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
