# Generated by Django 5.0.4 on 2024-06-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_allequipment_equipment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentonmission',
            name='equipment_description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='equipmentonmission',
            name='equipment_model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='equipmentonmission',
            name='equipment_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='allequipment',
            name='equipment_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='allequipment',
            name='equipment_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
