# Generated by Django 5.0.4 on 2024-06-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_allequipment_equipment_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclassification',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='userclassification',
            name='is_mechanic',
        ),
        migrations.AddField(
            model_name='userclassification',
            name='job',
            field=models.IntegerField(blank=True, choices=[(1, 'User'), (2, 'Mechanic')], null=True),
        ),
    ]
