# Generated by Django 5.0.4 on 2024-06-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_userclassification_is_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentonmission',
            name='equipment_category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
