# Generated by Django 5.0.4 on 2024-06-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_equipmentonmission_equipment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allequipment',
            name='is_available',
        ),
        migrations.AddField(
            model_name='allequipment',
            name='equipment_status',
            field=models.IntegerField(blank=True, choices=[(1, 'In-service'), (2, 'Available'), (3, 'Maintenance-needed'), (4, 'Damaged')], null=True),
        ),
    ]
