# Generated by Django 5.0.4 on 2024-06-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_allequipment_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allequipment',
            name='equipment_status',
        ),
    ]
