# Generated by Django 5.0.4 on 2024-06-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_allequipment_equipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentonmission',
            name='equipment_id1',
            field=models.CharField(default='', max_length=100),
        ),
    ]
