# Generated by Django 5.0.4 on 2024-06-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_equipmentonmission_equipment_id1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentonmission',
            old_name='equipment',
            new_name='all_equipment',
        ),
        migrations.RenameField(
            model_name='equipmentonmission',
            old_name='equipment_id1',
            new_name='equipment_id_on_mission',
        ),
    ]
