# Generated by Django 5.0.4 on 2024-06-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_allequipment_equipment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allequipment',
            name='equipment_status',
        ),
    ]
