# Generated by Django 5.0.4 on 2024-06-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_damagedequipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damagedequipment',
            old_name='all_equipment1',
            new_name='all_equipment',
        ),
    ]
