# Generated by Django 5.0.4 on 2024-06-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_all_equipment1_damagedequipment_all_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='allequipment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'To pack'), (2, 'To ship'), (3, 'To deliver'), (4, 'Canceled')], null=True),
        ),
    ]
